package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/srcfl/ftw/go/internal/config"
	"github.com/srcfl/ftw/go/internal/control"
	"github.com/srcfl/ftw/go/internal/drivers"
	"github.com/srcfl/ftw/go/internal/loadmodel"
	"github.com/srcfl/ftw/go/internal/modelstate"
	"github.com/srcfl/ftw/go/internal/pvmodel"
	"github.com/srcfl/ftw/go/internal/state"
	"github.com/srcfl/ftw/go/internal/telemetry"
)

// FTW #1229: malformed overrides must not raise known per-driver limits.
func TestBeta4AuditBothZeroKeepsKnownDriverCaps(t *testing.T) {
	cfg := parseBatteryLimitConfig(t,
		"    max_charge_w: 2000\n    max_discharge_w: 3000\n",
		"    max_charge_w: 0\n    max_discharge_w: 0\n")
	ctrl := newControlStateFromConfig(cfg)
	ctrl.Mode = control.ModeCharge
	targets := control.ComputeDispatch(batteryLimitStore(0), ctrl, map[string]float64{"battery": 10000}, 40000)
	if len(targets) != 1 || targets[0].TargetW > 2000 {
		t.Fatalf("known 2000 W driver charge cap exceeded: limits=%+v dispatch=%+v", ctrl.DriverLimits["battery"], targets)
	}
}

func TestBeta4AuditPlannerAndControlKeepEachKnownBatteryLimit(t *testing.T) {
	for _, tc := range []struct {
		name, driver      string
		charge, discharge float64
	}{
		{"both known", "    max_charge_w: 2000\n    max_discharge_w: 3000\n", 2000, 3000},
		{"charge known", "    max_charge_w: 2000\n", 2000, 5000},
		{"discharge known", "    max_discharge_w: 3000\n", 5000, 3000},
		{"neither known", "", 5000, 5000},
	} {
		t.Run(tc.name, func(t *testing.T) {
			cfg := parseBatteryLimitConfig(t, tc.driver, "    max_charge_w: 0\n    max_discharge_w: 0\n")
			ctrl := newControlStateFromConfig(cfg).DriverLimits["battery"]
			fleet := mpcBatteryFleetFromConfig(cfg, map[string]float64{"battery": 10000})
			if ctrl.MaxChargeW != tc.charge || ctrl.MaxDischargeW != tc.discharge || len(fleet) != 1 || fleet[0].MaxChargeW != tc.charge || fleet[0].MaxDischargeW != tc.discharge {
				t.Fatalf("planner/control limits differ from known caps: control=%+v fleet=%+v", ctrl, fleet)
			}
		})
	}
}

// FTW #1230. The binding fixture was generated by v3.4.2-beta.3 (6716619e), with
// exactly the config/identities below and TZ=UTC. Script files were absent,
// as in a temporarily unavailable driver directory. Do not regenerate the
// fixture with current Configure: that would stop testing an upgrade.
func TestBeta4AuditUpgradePreservesForecastLearning(t *testing.T) {
	t.Setenv("TZ", "UTC")
	raw, err := os.ReadFile("testdata/beta3-forecast-binding.json")
	if err != nil {
		t.Fatal(err)
	}
	var old struct {
		Learning, Evaluation string
		Receipt              json.RawMessage
	}
	if err := json.Unmarshal(raw, &old); err != nil {
		t.Fatal(err)
	}
	for _, signal := range []string{"pv", "load"} {
		t.Run(signal, func(t *testing.T) {
			st, err := state.Open(filepath.Join(t.TempDir(), "state.db"))
			if err != nil {
				t.Fatal(err)
			}
			defer st.Close()
			save := func(key string, value any, feature string) {
				t.Helper()
				encoded, err := modelstate.Wrap(feature, value)
				if err != nil {
					t.Fatal(err)
				}
				if err := st.SaveConfig(key, string(encoded)); err != nil {
					t.Fatal(err)
				}
			}
			pv := pvmodel.NewModel(5000)
			pv.ConfigRevision, pv.Samples = old.Learning, 85
			save("pvmodel/state_utc", pv, pvmodel.FeatureHash())
			for _, profile := range loadmodel.Profiles() {
				m := loadmodel.NewModel(4000)
				m.ConfigRevision, m.Timezone, m.Samples = old.Learning, "UTC", 85
				save("loadmodel/state_utc:"+string(profile), m, loadmodel.FeatureHash())
			}
			for key, value := range map[string]string{
				forecastIdentityReceiptKey: string(old.Receipt),
				"forecast/config_revision": old.Evaluation,
				"loadmodel/timezone":       "UTC",
			} {
				if err := st.SaveConfig(key, value); err != nil {
					t.Fatal(err)
				}
			}
			cfg := &config.Config{Drivers: []config.Driver{
				{Name: "meter", Lua: "audit-meter.lua", IsSiteMeter: true},
				{Name: "ev", Lua: "audit-ev.lua"},
			}, Weather: &config.Weather{Provider: "open_meteo", Latitude: 59, Longitude: 18}}
			catalog := []drivers.CatalogEntry{
				{Filename: "audit-meter.lua", Capabilities: []string{"meter", "pv", "battery"}},
				{Filename: "audit-ev.lua", Capabilities: []string{"ev"}},
			}
			s := newForecastSiteConfig(st)
			s.identity = func(name string) (string, bool) { return name + ":serial-fixture", true }
			s.Configure(cfg, catalog)
			next := s.Snapshot()
			if next.IdentityPending {
				t.Fatal("unchanged hardware identity stayed pending")
			}
			tele := telemetry.NewStore()
			var samples int64
			if signal == "pv" {
				cs := func(time.Time) float64 { return 1000 }
				m := pvmodel.NewService(st, tele, cs, nil, 5000)
				m.Reconfigure(cs, next.LearningRevision)
				samples = m.Model().Samples
			} else {
				m := loadmodel.NewService(st, tele, "meter", 4000, 0)
				if err := m.Reconfigure(next.Meter, next.Options, next.Timezone, next.LearningRevision); err != nil {
					t.Fatal(err)
				}
				samples = m.Model().Samples
			}
			if samples != 85 {
				t.Fatalf("compatible beta.3 upgrade lost %s learning: samples=%d, want 85; old=%s new=%s", signal, samples, old.Learning, next.LearningRevision)
			}
			restarted := newForecastSiteConfig(st)
			restarted.identity = s.identity
			restarted.Configure(cfg, catalog)
			if got := restarted.Snapshot(); got.IdentityPending || got.LearningRevision != old.Learning {
				t.Fatalf("compatible learning binding changed after restart: %+v", got)
			}
			cfg.Drivers[1].Config = map[string]any{"control_default": "new"}
			restarted.engineVersion = "next-worker"
			restarted.Configure(cfg, catalog)
			if got := restarted.Snapshot(); got.LearningRevision != old.Learning {
				t.Fatal("later charger setting or worker version discarded migrated learning")
			}
			cfg.Drivers[0].Config = map[string]any{"scale": 2}
			restarted.Configure(cfg, catalog)
			if restarted.Snapshot().LearningRevision == old.Learning {
				t.Fatal("migration alias hid a real meter scaling change")
			}
		})
	}
}
