"""Roof segmentation tests.

Every case is a synthetic roof whose tilt, azimuth and area are known exactly by
construction, so the assertions check recovered geometry against ground truth
rather than against a previous run's output.
"""

import math

import numpy as np
import pytest

from ftw_roofmodel.segment import RoofPlane, segment_roof


def make_plane(
    *,
    tilt_deg: float,
    azimuth_deg: float,
    width: float = 10.0,
    depth: float = 8.0,
    origin=(0.0, 0.0, 0.0),
    density: float = 8.0,
    noise_m: float = 0.0,
    seed: int = 1,
) -> np.ndarray:
    """Sample a rectangular sloped surface with a known tilt and azimuth.

    The surface is generated by taking a horizontal grid and raising it along
    the downslope direction, which is the inverse of what segment_roof does, so
    the test never shares an implementation with the code under test.
    """
    rng = np.random.default_rng(seed)
    n = max(int(width * depth * density), 60)
    x = rng.uniform(0, width, n)
    y = rng.uniform(0, depth, n)

    # Aspect points the way the surface faces; height falls off along it.
    az = math.radians(azimuth_deg)
    east_dir, north_dir = math.sin(az), math.cos(az)
    slope = math.tan(math.radians(tilt_deg))
    z = -(x * east_dir + y * north_dir) * slope

    if noise_m:
        z = z + rng.normal(0.0, noise_m, n)

    return np.column_stack([x + origin[0], y + origin[1], z + origin[2]])


@pytest.mark.parametrize(
    "tilt,azimuth",
    [
        (35.0, 180.0),  # classic south-facing pitched roof
        (30.0, 90.0),   # east
        (30.0, 270.0),  # west
        (45.0, 0.0),    # north
        (20.0, 225.0),  # south-west
        (60.0, 135.0),  # steep south-east
    ],
)
def test_recovers_known_tilt_and_azimuth(tilt, azimuth):
    cloud = make_plane(tilt_deg=tilt, azimuth_deg=azimuth)
    planes = segment_roof(cloud, point_density=8.0)
    assert planes, "expected at least one plane"
    got = planes[0]
    assert got.tilt_deg == pytest.approx(tilt, abs=1.5)
    # Compare on the circle so 359.5 vs 0.5 is a 1-degree error, not 359.
    delta = abs((got.azimuth_deg - azimuth + 180.0) % 360.0 - 180.0)
    assert delta < 2.0, f"azimuth {got.azimuth_deg} vs {azimuth}"


def test_flat_roof_reports_flat_and_does_not_invent_an_azimuth():
    """A horizontal surface has no meaningful aspect: its normal is vertical,
    so the horizontal component is pure noise and could point anywhere."""
    cloud = make_plane(tilt_deg=0.0, azimuth_deg=180.0, noise_m=0.02)
    planes = segment_roof(cloud, point_density=8.0)
    assert planes
    assert planes[0].tilt_deg < 5.0
    assert planes[0].azimuth_deg == 180.0


def test_gable_roof_splits_into_two_opposing_faces():
    """The canonical case: one ridge, two faces 180 degrees apart."""
    south = make_plane(tilt_deg=35, azimuth_deg=180, depth=6, origin=(0, 0, 0), seed=2)
    north = make_plane(tilt_deg=35, azimuth_deg=0, depth=6, origin=(0, 6, -4.2), seed=3)
    planes = segment_roof(np.vstack([south, north]), point_density=8.0)

    assert len(planes) >= 2, f"expected two faces, got {len(planes)}"
    azimuths = sorted(p.azimuth_deg for p in planes[:2])
    opposed = abs((azimuths[1] - azimuths[0]) - 180.0)
    assert opposed < 5.0, f"faces should oppose, got {azimuths}"
    for p in planes[:2]:
        assert p.tilt_deg == pytest.approx(35.0, abs=2.0)


def test_two_separate_buildings_on_the_same_plane_are_split():
    """Two roofs with identical pitch and aspect satisfy one plane equation.
    RANSAC alone would merge them; the DBSCAN pass is what separates them."""
    a = make_plane(tilt_deg=30, azimuth_deg=180, origin=(0, 0, 0), seed=4)
    b = make_plane(tilt_deg=30, azimuth_deg=180, origin=(60, 0, 0), seed=5)
    planes = segment_roof(np.vstack([a, b]), point_density=8.0, cluster_eps_m=1.5)

    assert len(planes) >= 2, "spatially disjoint faces must not be merged"
    for p in planes[:2]:
        assert p.tilt_deg == pytest.approx(30.0, abs=2.0)


def test_area_is_the_sloped_area_not_the_footprint():
    """A 10x8 footprint at 60 degrees covers 80 / cos(60) = 160 m2 of roof."""
    cloud = make_plane(tilt_deg=60.0, azimuth_deg=180.0, width=10, depth=8, density=10)
    planes = segment_roof(cloud, point_density=10.0)
    assert planes
    assert planes[0].area_m2 == pytest.approx(160.0, rel=0.15)


def test_area_of_a_flat_roof_matches_its_footprint():
    cloud = make_plane(tilt_deg=0.0, azimuth_deg=180.0, width=12, depth=10, density=10)
    planes = segment_roof(cloud, point_density=10.0)
    assert planes
    assert planes[0].area_m2 == pytest.approx(120.0, rel=0.15)


def test_survives_realistic_measurement_noise():
    """1-2 pts/m2 airborne LiDAR carries several centimetres of range noise."""
    cloud = make_plane(tilt_deg=35.0, azimuth_deg=180.0, noise_m=0.05, density=6)
    planes = segment_roof(cloud, point_density=6.0, threshold_m=0.3)
    assert planes
    assert planes[0].tilt_deg == pytest.approx(35.0, abs=3.0)


def test_walls_are_rejected():
    """A near-vertical surface is a wall or a dormer cheek, not a roof."""
    cloud = make_plane(tilt_deg=88.0, azimuth_deg=180.0)
    planes = segment_roof(cloud, point_density=8.0)
    assert all(p.tilt_deg <= 80.0 for p in planes)


def test_noise_alone_yields_nothing_believable():
    """A handful of scattered returns must not become a roof."""
    rng = np.random.default_rng(7)
    cloud = rng.uniform(0, 10, size=(25, 3))
    assert segment_roof(cloud, point_density=8.0) == []


def test_is_deterministic():
    """Re-running a derive must not shuffle an operator's arrays."""
    cloud = make_plane(tilt_deg=35, azimuth_deg=180)
    a = segment_roof(cloud, point_density=8.0)
    b = segment_roof(cloud, point_density=8.0)
    assert a == b


def test_planes_are_ordered_by_area():
    big = make_plane(tilt_deg=30, azimuth_deg=180, width=14, depth=12, origin=(0, 0, 0), seed=8)
    small = make_plane(tilt_deg=30, azimuth_deg=180, width=5, depth=4, origin=(70, 0, 0), seed=9)
    planes = segment_roof(np.vstack([big, small]), point_density=8.0)
    assert len(planes) >= 2
    assert planes[0].area_m2 >= planes[1].area_m2


def test_rejects_malformed_input():
    with pytest.raises(ValueError):
        segment_roof(np.zeros((10, 2)))


def test_kwp_derives_from_area_with_packing_losses():
    """A 100 m2 face cannot carry 100 m2 of modules."""
    plane = RoofPlane(tilt_deg=35, azimuth_deg=180, area_m2=100.0, point_count=800, mean_height_m=6.0)
    kwp = plane.kwp()
    assert kwp == pytest.approx(100 * 0.70 * 200 / 1000.0)
    assert kwp < 100 * 200 / 1000.0, "packing factor must reduce the raw area"


def test_kwp_scales_with_area():
    a = RoofPlane(tilt_deg=35, azimuth_deg=180, area_m2=50.0, point_count=1, mean_height_m=1.0)
    b = RoofPlane(tilt_deg=35, azimuth_deg=180, area_m2=100.0, point_count=1, mean_height_m=1.0)
    assert b.kwp() == pytest.approx(2 * a.kwp())


def test_azimuth_never_reports_360():
    """A north face fits at ~359.97 deg, which rounds to 360.0 -- the same
    direction as 0 but an out-of-range-looking value for anything consuming it.
    Caught by the demo, so pinned here."""
    cloud = make_plane(tilt_deg=35, azimuth_deg=0, seed=21)
    planes = segment_roof(cloud, point_density=8.0)
    assert planes
    for p in planes:
        assert 0.0 <= p.azimuth_deg < 360.0, p.azimuth_deg
