// Package gencontract turns contract/registry.yaml into Go constants.
//
// The registry is the one place a name shared with the app is written down.
// Hand-copying those names is how this codebase ended up with three separate
// authorisation namespaces, so the box reads the file instead of retyping it.
//
// Run it with `go generate ./internal/appproto/...`.
package gencontract

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Registry is the subset of the YAML the box needs. Fields the app owns alone
// (roles, carrier states) are deliberately absent: generating a constant the
// box never uses only invites someone to use it.
type Registry struct {
	Version      int `yaml:"version"`
	FrozenFields map[int]struct {
		Name string `yaml:"name"`
		Kind string `yaml:"kind"`
		Unit string `yaml:"unit"`
	} `yaml:"frozen_fields"`
	Capabilities []string `yaml:"capabilities"`
	Scopes       []struct {
		Name string `yaml:"name"`
		Desc string `yaml:"desc"`
	} `yaml:"scopes"`
	Modes []struct {
		Key  string `yaml:"key"`
		Tier string `yaml:"tier"`
	} `yaml:"modes"`
	Errors []struct {
		Code      string `yaml:"code"`
		Retryable bool   `yaml:"retryable"`
		Desc      string `yaml:"desc"`
	} `yaml:"errors"`
	SourceStates []string `yaml:"source_states"`
	Resolutions  map[string]struct {
		TileSpanMs    int64  `yaml:"tile_span_ms"`
		RetentionDays int    `yaml:"retention_days"`
		Source        string `yaml:"source"`
	} `yaml:"resolutions"`
}

// Generate renders the constant file. Exported and byte-deterministic so the
// drift test can re-run it in memory and compare, rather than shelling out.
func Generate(raw []byte) ([]byte, error) {
	var reg Registry
	if err := yaml.Unmarshal(raw, &reg); err != nil {
		return nil, fmt.Errorf("parse registry: %w", err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by gencontract from contract/registry.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package appproto\n\n")

	fmt.Fprintf(&b, "// ContractVersion is the registry revision these names came from.\n")
	fmt.Fprintf(&b, "const ContractVersion = %d\n\n", reg.Version)

	writeFields(&b, reg)
	writeCaps(&b, reg)
	writeScopes(&b, reg)
	writeErrors(&b, reg)
	writeSourceStates(&b, reg)
	writeResolutions(&b, reg)
	writeRegistryModes(&b, reg)

	return format.Source(b.Bytes())
}

func writeFields(b *bytes.Buffer, reg Registry) {
	ids := make([]int, 0, len(reg.FrozenFields))
	for id := range reg.FrozenFields {
		ids = append(ids, id)
	}
	sort.Ints(ids)

	b.WriteString("// Fid is a telemetry field id. 1-9 are frozen permanently as of v1, so an\n")
	b.WriteString("// app of any age can draw the core view from them alone.\n")
	b.WriteString("type Fid uint32\n\n")
	b.WriteString("const (\n")
	for _, id := range ids {
		f := reg.FrozenFields[id]
		unit := f.Unit
		if unit == "" {
			unit = "none"
		}
		fmt.Fprintf(b, "\t// Fid%s — %s, unit %s.\n", goName(f.Name), f.Kind, unit)
		fmt.Fprintf(b, "\tFid%s Fid = %d\n", goName(f.Name), id)
	}
	b.WriteString(")\n\n")

	b.WriteString("// FrozenFieldNames maps a frozen field id to its registry name.\n")
	b.WriteString("var FrozenFieldNames = map[Fid]string{\n")
	for _, id := range ids {
		fmt.Fprintf(b, "\tFid%s: %q,\n", goName(reg.FrozenFields[id].Name), reg.FrozenFields[id].Name)
	}
	b.WriteString("}\n\n")

	b.WriteString("// FrozenFieldUnits maps a frozen field id to its unit, empty when it has none.\n")
	b.WriteString("var FrozenFieldUnits = map[Fid]string{\n")
	for _, id := range ids {
		fmt.Fprintf(b, "\tFid%s: %q,\n", goName(reg.FrozenFields[id].Name), reg.FrozenFields[id].Unit)
	}
	b.WriteString("}\n\n")
}

func writeCaps(b *bytes.Buffer, reg Registry) {
	b.WriteString("// Capabilities are presence, not levels. An app hides what is absent and\n")
	b.WriteString("// never compares versions.\n")
	b.WriteString("const (\n")
	for _, c := range reg.Capabilities {
		fmt.Fprintf(b, "\tCap%s = %q\n", goName(c), c)
	}
	b.WriteString(")\n\n")

	b.WriteString("// AllCapabilities is every capability name the registry defines.\n")
	b.WriteString("var AllCapabilities = []string{\n")
	for _, c := range reg.Capabilities {
		fmt.Fprintf(b, "\tCap%s,\n", goName(c))
	}
	b.WriteString("}\n\n")
}

func writeScopes(b *bytes.Buffer, reg Registry) {
	b.WriteString("// Scopes are one object axis and two verb axes. Roles are a projection over\n")
	b.WriteString("// these, never a replacement for them.\n")
	b.WriteString("const (\n")
	for _, s := range reg.Scopes {
		fmt.Fprintf(b, "\t// Scope%s — %s.\n", goName(strings.TrimPrefix(s.Name, "ftw.")), s.Desc)
		fmt.Fprintf(b, "\tScope%s = %q\n", goName(strings.TrimPrefix(s.Name, "ftw.")), s.Name)
	}
	b.WriteString(")\n\n")
}

func writeErrors(b *bytes.Buffer, reg Registry) {
	b.WriteString("// Error codes. The box sends the code and machine-readable args; the app\n")
	b.WriteString("// owns every word of prose, in every language it ships.\n")
	b.WriteString("const (\n")
	for _, e := range reg.Errors {
		fmt.Fprintf(b, "\t// %s — %s.\n", errName(e.Code), e.Desc)
		fmt.Fprintf(b, "\t%s = %q\n", errName(e.Code), e.Code)
	}
	b.WriteString(")\n\n")

	b.WriteString("// ErrorRetryable reports whether the app should offer a retry for a code.\n")
	b.WriteString("var ErrorRetryable = map[string]bool{\n")
	for _, e := range reg.Errors {
		fmt.Fprintf(b, "\t%s: %t,\n", errName(e.Code), e.Retryable)
	}
	b.WriteString("}\n\n")
}

func writeSourceStates(b *bytes.Buffer, reg Registry) {
	b.WriteString("// SourceState says whether a device is answering. It is orthogonal to the\n")
	b.WriteString("// carrier state: \"connected, but the inverter went quiet\" needs both.\n")
	b.WriteString("type SourceState string\n\n")
	b.WriteString("const (\n")
	for _, s := range reg.SourceStates {
		fmt.Fprintf(b, "\tSource%s SourceState = %q\n", goName(s), s)
	}
	b.WriteString(")\n\n")
}

func writeResolutions(b *bytes.Buffer, reg Registry) {
	keys := make([]string, 0, len(reg.Resolutions))
	for k := range reg.Resolutions {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	b.WriteString("// Resolution is a history resolution the box actually stores.\n")
	b.WriteString("type Resolution string\n\n")
	b.WriteString("const (\n")
	for _, k := range keys {
		fmt.Fprintf(b, "\t// Res%s comes from the %s.\n", goName(k), reg.Resolutions[k].Source)
		fmt.Fprintf(b, "\tRes%s Resolution = %q\n", goName(k), k)
	}
	b.WriteString(")\n\n")

	b.WriteString("// ResolutionTileSpanMs is how much time one transfer tile covers.\n")
	b.WriteString("var ResolutionTileSpanMs = map[Resolution]int64{\n")
	for _, k := range keys {
		fmt.Fprintf(b, "\tRes%s: %d,\n", goName(k), reg.Resolutions[k].TileSpanMs)
	}
	b.WriteString("}\n\n")

	b.WriteString("// ResolutionRetentionDays is how far back the box keeps a resolution.\n")
	b.WriteString("var ResolutionRetentionDays = map[Resolution]int{\n")
	for _, k := range keys {
		fmt.Fprintf(b, "\tRes%s: %d,\n", goName(k), reg.Resolutions[k].RetentionDays)
	}
	b.WriteString("}\n\n")
}

func writeRegistryModes(b *bytes.Buffer, reg Registry) {
	b.WriteString("// RegistryModeTiers is the app's copy of this repository's mode tiers.\n")
	b.WriteString("// control.ModeCatalog() remains the authority — this exists only so\n")
	b.WriteString("// TestRegistryModesMatchCatalog can catch the two drifting apart.\n")
	b.WriteString("var RegistryModeTiers = map[string]string{\n")
	for _, m := range reg.Modes {
		fmt.Fprintf(b, "\t%q: %q,\n", m.Key, m.Tier)
	}
	b.WriteString("}\n")
}

// errName turns E_CMD_EXPIRED into ErrCmdExpired.
func errName(code string) string {
	return "Err" + goName(strings.ToLower(strings.TrimPrefix(code, "E_")))
}

// goName turns a registry name into an exported Go identifier: dots,
// underscores and hyphens are word breaks, and a leading digit gets a prefix
// because "5m" is not an identifier.
func goName(s string) string {
	var out strings.Builder
	upper := true
	for _, r := range s {
		switch r {
		case '.', '_', '-':
			upper = true
		default:
			if upper {
				out.WriteString(strings.ToUpper(string(r)))
				upper = false
			} else {
				out.WriteRune(r)
			}
		}
	}
	name := out.String()
	if name != "" && name[0] >= '0' && name[0] <= '9' {
		name = "N" + name
	}
	return name
}
