// Code generated by gencontract from contract/registry.yaml. DO NOT EDIT.

package appproto

// ContractVersion is the registry revision these names came from.
const ContractVersion = 1

// Fid is a telemetry field id. 1-9 are frozen permanently as of v1, so an
// app of any age can draw the core view from them alone.
type Fid uint32

const (
	// FidMode — enum, unit none.
	FidMode Fid = 1
	// FidGridW — power, unit W.
	FidGridW Fid = 2
	// FidPvW — power, unit W.
	FidPvW Fid = 3
	// FidBatteryW — power, unit W.
	FidBatteryW Fid = 4
	// FidBatterySoc — ratio, unit permille.
	FidBatterySoc Fid = 5
	// FidLoadW — power, unit W.
	FidLoadW Fid = 6
	// FidSrcGrid — source_ref, unit none.
	FidSrcGrid Fid = 7
	// FidSrcPv — source_ref, unit none.
	FidSrcPv Fid = 8
	// FidSrcBattery — source_ref, unit none.
	FidSrcBattery Fid = 9
)

// FrozenFieldNames maps a frozen field id to its registry name.
var FrozenFieldNames = map[Fid]string{
	FidMode:       "mode",
	FidGridW:      "grid_w",
	FidPvW:        "pv_w",
	FidBatteryW:   "battery_w",
	FidBatterySoc: "battery_soc",
	FidLoadW:      "load_w",
	FidSrcGrid:    "src_grid",
	FidSrcPv:      "src_pv",
	FidSrcBattery: "src_battery",
}

// FrozenFieldUnits maps a frozen field id to its unit, empty when it has none.
var FrozenFieldUnits = map[Fid]string{
	FidMode:       "",
	FidGridW:      "W",
	FidPvW:        "W",
	FidBatteryW:   "W",
	FidBatterySoc: "permille",
	FidLoadW:      "W",
	FidSrcGrid:    "",
	FidSrcPv:      "",
	FidSrcBattery: "",
}

// Capabilities are presence, not levels. An app hides what is absent and
// never compares versions.
const (
	CapStatusCore      = "status.core"
	CapStatusPhases    = "status.phases"
	CapStatusDrivers   = "status.drivers"
	CapHistory5m       = "history.5m"
	CapHistory1h       = "history.1h"
	CapHistoryEtag     = "history.etag"
	CapCmdLease        = "cmd.lease"
	CapCmdPrecondition = "cmd.precondition"
	CapCmdReadback     = "cmd.readback"
	CapDerBattery      = "der.battery"
	CapDerEv           = "der.ev"
	CapDerV2x          = "der.v2x"
	CapPlanDispatch    = "plan.dispatch"
	CapNetWebrtc       = "net.webrtc"
)

// AllCapabilities is every capability name the registry defines.
var AllCapabilities = []string{
	CapStatusCore,
	CapStatusPhases,
	CapStatusDrivers,
	CapHistory5m,
	CapHistory1h,
	CapHistoryEtag,
	CapCmdLease,
	CapCmdPrecondition,
	CapCmdReadback,
	CapDerBattery,
	CapDerEv,
	CapDerV2x,
	CapPlanDispatch,
	CapNetWebrtc,
}

// Scopes are one object axis and two verb axes. Roles are a projection over
// these, never a replacement for them.
const (
	// ScopeLiveRead — Current readings and freshness.
	ScopeLiveRead = "ftw.live.read"
	// ScopeHistoryRead — Stored history.
	ScopeHistoryRead = "ftw.history.read"
	// ScopePlanRead — Dispatch plan and its reasoning.
	ScopePlanRead = "ftw.plan.read"
	// ScopeHealthRead — Box and driver health.
	ScopeHealthRead = "ftw.health.read"
	// ScopeAssetsRead — Devices and their capabilities.
	ScopeAssetsRead = "ftw.assets.read"
	// ScopeDispatchWrite — Control energy assets.
	ScopeDispatchWrite = "ftw.dispatch.write"
	// ScopeModeWrite — Change site operating mode.
	ScopeModeWrite = "ftw.mode.write"
	// ScopeMembersRead — See who has access.
	ScopeMembersRead = "ftw.members.read"
	// ScopeMembersWrite — Invite and revoke.
	ScopeMembersWrite = "ftw.members.write"
)

// Error codes. The box sends the code and machine-readable args; the app
// owns every word of prose, in every language it ships.
const (
	// ErrBooting — Box is starting up.
	ErrBooting = "E_BOOTING"
	// ErrUnknownOp — Message type not understood.
	ErrUnknownOp = "E_UNKNOWN_OP"
	// ErrCmdExpired — Command outlived not_valid_after_ms.
	ErrCmdExpired = "E_CMD_EXPIRED"
	// ErrPrecondition — Guard failed against fresh state.
	ErrPrecondition = "E_PRECONDITION"
	// ErrConflict — expect.rev did not match.
	ErrConflict = "E_CONFLICT"
	// ErrScopeDenied — Grant lacks the required scope.
	ErrScopeDenied = "E_SCOPE_DENIED"
	// ErrGrantRevoked — Access was withdrawn.
	ErrGrantRevoked = "E_GRANT_REVOKED"
	// ErrLastOwnerProtected — Cannot remove the only owner.
	ErrLastOwnerProtected = "E_LAST_OWNER_PROTECTED"
	// ErrRangeTooLarge — History window exceeds the limit.
	ErrRangeTooLarge = "E_RANGE_TOO_LARGE"
	// ErrUnavailable — Source or subsystem is down.
	ErrUnavailable = "E_UNAVAILABLE"
)

// ErrorRetryable reports whether the app should offer a retry for a code.
var ErrorRetryable = map[string]bool{
	ErrBooting:            true,
	ErrUnknownOp:          false,
	ErrCmdExpired:         false,
	ErrPrecondition:       false,
	ErrConflict:           true,
	ErrScopeDenied:        false,
	ErrGrantRevoked:       false,
	ErrLastOwnerProtected: false,
	ErrRangeTooLarge:      false,
	ErrUnavailable:        true,
}

// SourceState says whether a device is answering. It is orthogonal to the
// carrier state: "connected, but the inverter went quiet" needs both.
type SourceState string

const (
	SourceLive    SourceState = "live"
	SourceLagging SourceState = "lagging"
	SourceStale   SourceState = "stale"
	SourceDown    SourceState = "down"
	SourceNever   SourceState = "never"
)

// Resolution is a history resolution the box actually stores.
type Resolution string

const (
	// ResN1h comes from the hourly_rollup.
	ResN1h Resolution = "1h"
	// ResN5m comes from the energy_ledger.
	ResN5m Resolution = "5m"
)

// ResolutionTileSpanMs is how much time one transfer tile covers.
var ResolutionTileSpanMs = map[Resolution]int64{
	ResN1h: 604800000,
	ResN5m: 43200000,
}

// ResolutionRetentionDays is how far back the box keeps a resolution.
var ResolutionRetentionDays = map[Resolution]int{
	ResN1h: 730,
	ResN5m: 30,
}

// RegistryModeTiers is the app's copy of this repository's mode tiers.
// control.ModeCatalog() remains the authority — this exists only so
// TestRegistryModesMatchCatalog can catch the two drifting apart.
var RegistryModeTiers = map[string]string{
	"planner_passive_arbitrage": "primary",
	"planner_arbitrage":         "primary",
	"idle":                      "advanced",
	"self_consumption":          "advanced",
	"peak_shaving":              "advanced",
	"charge":                    "advanced",
	"planner_self":              "hidden",
	"planner_cheap":             "hidden",
	"priority":                  "hidden",
	"weighted":                  "hidden",
}
