package appproto

import (
	"context"
	"encoding/binary"
	"math"
	"testing"
	"time"

	"github.com/srcfl/ftw/go/internal/control"
	"github.com/srcfl/ftw/go/internal/mpc"
)

// The geometry must match the app's src/lib/protocol/history.ts exactly —
// both ends compute tiles independently and meet on the etag. The reference
// values below were generated by running the app's own functions, so a
// mismatch here is a genuine wire break, not a test opinion.

func TestTileGeometryMatchesTheApp(t *testing.T) {
	if got := pointsPerTile(ResN5m); got != 144 {
		t.Fatalf("5m tile has %d points, the app says 144", got)
	}
	if got := pointsPerTile(ResN1h); got != 168 {
		t.Fatalf("1h tile has %d points, the app says 168", got)
	}

	// tileId: res/stride/tileIndex, epoch-aligned.
	at := int64(1_760_000_000_000)
	start := tileStartFor(ResN5m, at)
	if start%43_200_000 != 0 || start > at || at-start >= 43_200_000 {
		t.Fatalf("5m tile start %d is not the aligned tile containing %d", start, at)
	}
	if got, want := tileIDFor(ResN5m, 3, start), "5m/3/40740"; got != want {
		t.Fatalf("tileID = %q, want %q", got, want)
	}
}

func TestEtagMatchesTheAppByteForByte(t *testing.T) {
	// Values from the app's etagOf(), run on the same input.
	ascending := make([]byte, 16)
	for i := range ascending {
		ascending[i] = byte(i)
	}
	if got := etagOf(ascending); got != "c8fff215" {
		t.Fatalf("etag([0..15]) = %s, the app computes c8fff215", got)
	}
	if got := etagOf(nil); got != "811c9dc5" {
		t.Fatalf("etag(empty) = %s, the app computes 811c9dc5", got)
	}
}

func TestPlanHistoryQueryClampsAndStrides(t *testing.T) {
	// A day at 5m fits under 2000 points: two tiles, stride 1.
	day := planHistoryQuery(ResN5m, 1_760_000_000_000, 1_760_086_400_000, 2000)
	if day.res != ResN5m || day.stride != 1 {
		t.Fatalf("one day plan: res=%s stride=%d, want 5m stride 1", day.res, day.stride)
	}

	// Sixty days at 5m cannot fit even aggregated — the box clamps to the
	// coarser store rather than serving averages of averages.
	wide := planHistoryQuery(ResN5m, 1_760_000_000_000-60*86_400_000, 1_760_000_000_000, 2000)
	if wide.res != ResN1h {
		t.Fatalf("sixty day plan stayed on %s, want a clamp to 1h", wide.res)
	}

	// A tight cap first clamps to the coarser store — real data beats
	// averages of averages — and only then strides. A day under a 100-point
	// cap lands on 1h stride 2, exactly as the app's planQuery does.
	strided := planHistoryQuery(ResN5m, 1_760_000_000_000, 1_760_086_400_000, 100)
	if strided.res != ResN1h || strided.stride != 2 {
		t.Fatalf("100-point day: res=%s stride=%d, the app plans 1h stride 2", strided.res, strided.stride)
	}
	if pointsPerTile(strided.res)%strided.stride != 0 {
		t.Fatalf("stride %d does not divide the tile", strided.stride)
	}
	if strided.stepMs != resolutionStepMs[strided.res]*strided.stride {
		t.Fatalf("stepMs %d does not match stride %d at %s", strided.stepMs, strided.stride, strided.res)
	}
}

// fakeLedger serves one flat value per named series, on every bucket of the
// asked window — except holes, which it skips entirely, like the real ledger.
type fakeLedger struct {
	values map[string]float64
	holes  map[int64]bool
	calls  int
	err    error
}

func (f *fakeLedger) Series(
	_ context.Context, name string, stepMs, fromMs, toMs int64,
) ([]HistorySample, error) {
	f.calls++
	if f.err != nil {
		return nil, f.err
	}
	value, ok := f.values[name]
	if !ok {
		return nil, nil
	}
	var out []HistorySample
	for at := fromMs; at < toMs; at += stepMs {
		if f.holes[at] {
			continue
		}
		out = append(out, HistorySample{StartMs: at, W: value})
	}
	return out, nil
}

func newHistoryRig(t *testing.T, ledger HistoryProvider) (*Handler, *recorder, *fakeClock) {
	t.Helper()
	clock := &fakeClock{uptimeMs: 60_000, now: time.UnixMilli(1_760_000_000_000)}
	box := &fakeBox{
		identity:     Identity{ID: "ftw-0001", Build: "test", TZ: "Europe/Stockholm"},
		mode:         control.ModePlannerPassiveArbitrage,
		snap:         Snapshot{Mode: control.ModePlannerPassiveArbitrage, DispatchBlockedBy: []string{}},
		observedMode: control.ModePlannerPassiveArbitrage,
		observedOK:   true,
	}
	rec := &recorder{}
	h, err := New(Config{
		Clock: clock, Site: box, Info: box, Modes: box, Plans: box,
		History: ledger,
		Codec:   testCodec{}, Sender: rec,
		SrcGrid: "meter.p1", SrcPV: "meter.p1", SrcBattery: "meter.p1",
		NewLeaseID: func() string { return "lease-test" },
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	subscribe(t, h, rec)
	return h, rec, clock
}

func histChunks(rec *recorder) []HistChunk {
	var out []HistChunk
	for _, f := range rec.frames {
		if f.env.T != MsgHistChunk {
			continue
		}
		var c HistChunk
		if err := Unmarshal(f.env.B, &c); err == nil {
			out = append(out, c)
		}
	}
	return out
}

func TestHistQueryServesTilesAndAnEnd(t *testing.T) {
	ledger := &fakeLedger{values: map[string]float64{"grid_w": 1200, "pv_w": -800}}
	h, rec, clock := newHistoryRig(t, ledger)

	from := clock.now.UnixMilli() - 6*3_600_000
	deliver(t, h, MsgHistQuery, ptrU32(9), HistQuery{
		Series: []string{"grid_w", "pv_w"},
		Res:    ResN5m,
		FromMs: from,
		ToMs:   clock.now.UnixMilli(),
	})

	chunks := histChunks(rec)
	if len(chunks) == 0 {
		t.Fatalf("no chunks; frames: %s", rec.types())
	}
	end := rec.only(t, MsgHistEnd)
	if end.env.ID == nil || *end.env.ID != 9 {
		t.Fatalf("hist.end did not echo the request id: %v", end.env.ID)
	}
	e := body[HistEnd](t, end)
	if e.ResActual != ResN5m {
		t.Fatalf("resActual = %s, want 5m", e.ResActual)
	}
	if e.Gaps == nil {
		t.Fatal("gaps must be an empty list, never absent")
	}

	// The trailing tile contains "now" and must be marked partial.
	last := chunks[len(chunks)-1]
	if !last.Partial {
		t.Fatal("the tile containing now was not marked partial")
	}

	// Columns are int32 LE, one block per series, and a flat 1200 W series
	// must decode back to 1200 on a bucket inside the window.
	c := chunks[0]
	points := int(int64(len(c.Data)) / 4 / int64(len(c.Series)))
	idx := points - 1 // late in the first tile, safely inside the data
	grid := int32(binary.LittleEndian.Uint32(c.Data[idx*4:]))
	pv := int32(binary.LittleEndian.Uint32(c.Data[(points+idx)*4:]))
	if grid != 1200 || pv != -800 {
		t.Fatalf("decoded grid=%d pv=%d, want 1200 and -800", grid, pv)
	}
}

func TestHistQueryTurnsAbsentBucketsIntoMissing(t *testing.T) {
	holeAt := tileStartFor(ResN5m, 1_760_000_000_000-6*3_600_000)
	ledger := &fakeLedger{
		values: map[string]float64{"grid_w": 500},
		holes:  map[int64]bool{holeAt: true},
	}
	h, rec, clock := newHistoryRig(t, ledger)

	deliver(t, h, MsgHistQuery, ptrU32(2), HistQuery{
		Series: []string{"grid_w"},
		Res:    ResN5m,
		FromMs: clock.now.UnixMilli() - 6*3_600_000,
		ToMs:   clock.now.UnixMilli(),
	})

	c := histChunks(rec)[0]
	offset := (holeAt - c.StartMs) / c.StepMs
	got := int32(binary.LittleEndian.Uint32(c.Data[offset*4:]))
	if got != math.MinInt32 {
		t.Fatalf("a bucket the ledger never wrote decoded to %d, want MISSING", got)
	}
}

func TestHistQuerySkipsTilesTheAppAlreadyHolds(t *testing.T) {
	ledger := &fakeLedger{values: map[string]float64{"grid_w": 500}}
	h, rec, clock := newHistoryRig(t, ledger)

	from := clock.now.UnixMilli() - 18*3_600_000 // three tiles: two closed, one partial
	deliver(t, h, MsgHistQuery, ptrU32(3), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
	})
	first := histChunks(rec)

	var have []HistTileRef
	for _, c := range first {
		if !c.Partial {
			have = append(have, HistTileRef{TileID: c.TileID, Etag: c.Etag})
		}
	}
	if len(have) == 0 {
		t.Fatal("test needs at least one closed tile")
	}

	rec.reset()
	deliver(t, h, MsgHistQuery, ptrU32(4), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
		Have: have,
	})
	second := histChunks(rec)

	for _, c := range second {
		if c.Partial {
			continue
		}
		for _, ref := range have {
			if c.TileID == ref.TileID {
				t.Fatalf("tile %s was resent although the app holds it unchanged", c.TileID)
			}
		}
	}
	if !rec.has(MsgHistEnd) {
		t.Fatal("a fully cached query still ends with hist.end")
	}
}

func TestHistQueryWithoutAProviderSaysUnavailable(t *testing.T) {
	h, rec, clock := func() (*Handler, *recorder, *fakeClock) {
		h, _, rec, clock := newRig(t)
		subscribe(t, h, rec)
		return h, rec, clock
	}()
	_ = clock

	deliver(t, h, MsgHistQuery, ptrU32(5), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: 0, ToMs: 1,
	})

	e := rec.only(t, MsgError)
	if e.env.ID == nil || *e.env.ID != 5 {
		t.Fatal("the error is not addressed to the request that caused it")
	}
	b := body[ErrorBody](t, e)
	if b.Code != ErrUnavailable {
		t.Fatalf("code = %s, want %s", b.Code, ErrUnavailable)
	}
}

// The plan used to be the message that killed sessions: 193 optimizer slots
// encode past the largest bulk bucket, sendBulk errored, and the uplink
// dropped the session — which the app experienced as "the box hangs up
// whenever I open the plan". The fix truncates; this proves it.
func TestAnOversizedPlanIsTruncatedNotFatal(t *testing.T) {
	h, box, rec, clock := newRig(t)
	subscribe(t, h, rec)

	actions := make([]mpc.Action, 193)
	for i := range actions {
		actions[i] = mpc.Action{
			SlotStartMs: clock.now.UnixMilli() + int64(i)*900_000,
			SlotLenMin:  15,
			PriceOre:    115.27,
			BatteryW:    1067.98,
			GridW:       -516.65,
			Reason:      "absorb PV surplus",
		}
	}
	box.plan = &mpc.Plan{GeneratedAtMs: clock.now.UnixMilli(), Actions: actions}

	deliver(t, h, MsgPlanGet, ptrU32(7), nil)

	f := rec.only(t, MsgPlan)
	p := body[Plan](t, f)
	if len(p.Slots) >= 193 {
		t.Fatalf("%d slots went out; the full plan does not fit any bucket", len(p.Slots))
	}
	if len(p.Slots) < 96 {
		t.Fatalf("only %d slots survived; a day should fit", len(p.Slots))
	}
	// The nearest slots survive — the tail is what gets dropped.
	if p.Slots[0].StartMs != clock.now.UnixMilli() {
		t.Fatal("truncation dropped the head of the plan instead of the tail")
	}
}
