// Code generated by genshipped from drivers/BUNDLED_SOURCE.json. DO NOT EDIT.

package fleetping

// shippedDrivers are the driver types bundled with this build.
//
// An array rather than a slice, so it is fixed in every sense: the length
// is part of the type and nothing can append to it at run time.
var shippedDrivers = [40]string{
	"ambibox_v2x",
	"ctek",
	"ctek_hybrid",
	"ctek_v2",
	"deye",
	"easee_cloud",
	"esphome_dsmr",
	"ferroamp",
	"ferroamp_dc2_v2x",
	"ferroamp_modbus",
	"foxess_h3_smart",
	"fronius",
	"fronius_smart_meter",
	"goodwe",
	"growatt",
	"heishamon",
	"huawei",
	"kostal",
	"myuplink",
	"nibe_local",
	"pixii",
	"pixii_pv",
	"sdm630",
	"sma",
	"sma_pv",
	"sofar",
	"solaredge",
	"solaredge_legacy",
	"solaredge_pv",
	"solis",
	"solis_string",
	"sonnen",
	"sungrow",
	"tesla_vehicle",
	"tesla_wall_connector",
	"tibber",
	"victron",
	"zap",
	"zaptec_cloud",
	"zuidwijk_p1",
}
