package drivers

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A signed artifact does not write its DRIVER table inline. The generator in
// device-drivers builds it as a local and assigns it twice -- before the
// source loads and again after -- so a driver cannot overwrite the identity it
// was signed under.
//
// Parsing only the inline form made every signed driver read as empty
// metadata, and validateLuaArtifact rejected the install with
// "driver metadata id/version @, want ferroamp@1.1.1". Nothing from the
// channel could be installed at all: not Update, not a version switch.
const signedArtifact = `-- Generated by tools/ftw_repository.py from the public source and catalog.
-- This FTW v1 artifact is read-only even when another target has control.
local __sourceful_ftw_metadata = {
    id = "ferroamp",
    name = "Ferroamp",
    version = "1.1.1",
    host_api_min = 1,
    host_api_max = 1,
    protocols = { "mqtt" },
    capabilities = { "battery", "meter", "pv" },
    read_only = true,
    manufacturer = "Ferroamp",
    verification_status = "experimental",
}
DRIVER = __sourceful_ftw_metadata
local function __sourceful_ftw_write_denied()
    error("signed FTW community drivers are read-only")
end
host.mqtt_pub = __sourceful_ftw_write_denied

function driver_poll(ctx) return {} end

-- Enforce the signed FTW metadata and read-only lifecycle after source load.
DRIVER = __sourceful_ftw_metadata
`

func writeLua(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "driver.lua")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	return path
}

func TestParseCatalogFileFollowsSignedArtifactAlias(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, signedArtifact))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "ferroamp" || e.Version != "1.1.1" {
		t.Fatalf("id/version = %q@%q, want ferroamp@1.1.1 — the installer "+
			"compares these against the manifest and refuses the artifact when they are empty",
			e.ID, e.Version)
	}
	if !e.ReadOnly {
		t.Error("read_only must survive the alias: the installer checks it against the manifest")
	}
	if got, want := e.VerificationStatus, "experimental"; got != want {
		t.Errorf("VerificationStatus = %q, want %q", got, want)
	}
	if len(e.Capabilities) != 3 {
		t.Errorf("Capabilities = %v, want battery/meter/pv", e.Capabilities)
	}
}

// The bundled drivers write the table inline, and that must keep working.
func TestParseCatalogFileStillReadsInlineTable(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, `DRIVER = {
    id = "inline",
    version = "2.0.0",
    protocols = { "modbus" },
}

function driver_poll(ctx) return {} end
`))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "inline" || e.Version != "2.0.0" {
		t.Fatalf("id/version = %q@%q, want inline@2.0.0", e.ID, e.Version)
	}
}

// A signed artifact that wraps an FTW-native source carries BOTH forms: the
// generator's alias up front and at the end, and the source's own inline
// DRIVER table in between. Lua's last assignment wins, so the trailing alias
// — the identity the artifact was signed under — must beat the inline table
// even when the source block is stale. Preferring the inline form rejected
// myuplink@1.1.1 with "driver metadata id/version myuplink@1.0.0, want
// myuplink@1.1.1": the source still declared 1.0.0.
const wrappedNativeArtifact = `-- Generated by tools/ftw_repository.py from the public source and catalog.
local __sourceful_ftw_metadata = {
    id = "myuplink",
    name = "MyUplink Heat Pump (telemetry)",
    version = "1.1.1",
    host_api_min = 1,
    host_api_max = 1,
    protocols = { "http" },
}
DRIVER = __sourceful_ftw_metadata

-- The wrapped source declares its own identity, one release behind.
DRIVER = {
  id           = "myuplink",
  name         = "MyUplink Heat Pump (telemetry)",
  version      = "1.0.0",
  protocols    = { "http" },
}

function driver_poll(ctx) return {} end

-- Reassert the signed FTW identity after source load.
DRIVER = __sourceful_ftw_metadata
`

func TestParseCatalogFileSignedIdentityBeatsInlineSourceBlock(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, wrappedNativeArtifact))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "myuplink" || e.Version != "1.1.1" {
		t.Fatalf("id/version = %q@%q, want myuplink@1.1.1 — the trailing alias "+
			"is what DRIVER holds after the chunk runs, and what the artifact was signed under",
			e.ID, e.Version)
	}
}

// A source that writes its own inline table AFTER the trailing alias has
// overwritten the signed identity, and the parser must report that override
// so the installer can refuse the artifact against the manifest.
func TestParseCatalogFileReportsInlineOverrideAfterAlias(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, `local __sourceful_ftw_metadata = {
    id = "signed",
    version = "2.0.0",
}
DRIVER = __sourceful_ftw_metadata

function driver_poll(ctx) return {} end

DRIVER = __sourceful_ftw_metadata
DRIVER = {
    id = "override",
    version = "9.9.9",
}
`))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "override" || e.Version != "9.9.9" {
		t.Fatalf("id/version = %q@%q, want override@9.9.9 — the parser must see "+
			"what the VM would run, or a source could smuggle one identity past the manifest check",
			e.ID, e.Version)
	}
}

// An assignment that names nothing parseable should stay empty rather than
// pick up whatever table happens to be nearby.
func TestParseCatalogFileIgnoresAnAliasWithNoTable(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, `local other = {
    id = "not-the-driver",
    version = "9.9.9",
}
DRIVER = missing_table
`))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "" || e.Version != "" {
		t.Fatalf("id/version = %q@%q, want empty — a dangling alias must not "+
			"borrow another table's identity", e.ID, e.Version)
	}
}

// Lua never executes a commented-out assignment, so neither should the
// parser read one. With the last match winning, an example block left in a
// comment below the real one would otherwise become the driver's identity —
// dropping it from the catalog, or having its install refused against a
// manifest it never claimed. Codex P2 on PR #754.
func TestParseCatalogFileIgnoresCommentedDriverBlock(t *testing.T) {
	src := `DRIVER = {
    id = "real",
    name = "Real Driver",
    version = "1.2.3",
}

-- Example for driver authors:
-- DRIVER = {
--     id = "example",
--     name = "Example",
--     version = "9.9.9",
-- }

function driver_init() end
`
	got := extractDriverBlock(src)
	if !strings.Contains(got, `id = "real"`) {
		t.Fatalf("parser did not read the executed block, got:\n%s", got)
	}
	if strings.Contains(got, "9.9.9") {
		t.Errorf("parser read a commented-out block:\n%s", got)
	}
}

// The same applies to an indented block: Lua runs it, so the parser has to
// see it. Anchoring must not become "column 0 only".
func TestParseCatalogFileReadsIndentedDriverBlock(t *testing.T) {
	src := "  DRIVER = {\n    id = \"indented\",\n    version = \"1.0.0\",\n}\n"
	if got := extractDriverBlock(src); !strings.Contains(got, `id = "indented"`) {
		t.Errorf("indented block not read, got:\n%s", got)
	}
}
