package drivers

import (
	"os"
	"path/filepath"
	"testing"
)

// A signed artifact does not write its DRIVER table inline. The generator in
// device-drivers builds it as a local and assigns it twice -- before the
// source loads and again after -- so a driver cannot overwrite the identity it
// was signed under.
//
// Parsing only the inline form made every signed driver read as empty
// metadata, and validateLuaArtifact rejected the install with
// "driver metadata id/version @, want ferroamp@1.1.1". Nothing from the
// channel could be installed at all: not Update, not a version switch.
const signedArtifact = `-- Generated by tools/ftw_repository.py from the public source and catalog.
-- This FTW v1 artifact is read-only even when another target has control.
local __sourceful_ftw_metadata = {
    id = "ferroamp",
    name = "Ferroamp",
    version = "1.1.1",
    host_api_min = 1,
    host_api_max = 1,
    protocols = { "mqtt" },
    capabilities = { "battery", "meter", "pv" },
    read_only = true,
    manufacturer = "Ferroamp",
    verification_status = "experimental",
}
DRIVER = __sourceful_ftw_metadata
local function __sourceful_ftw_write_denied()
    error("signed FTW community drivers are read-only")
end
host.mqtt_pub = __sourceful_ftw_write_denied

function driver_poll(ctx) return {} end

-- Enforce the signed FTW metadata and read-only lifecycle after source load.
DRIVER = __sourceful_ftw_metadata
`

func writeLua(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "driver.lua")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	return path
}

func TestParseCatalogFileFollowsSignedArtifactAlias(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, signedArtifact))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "ferroamp" || e.Version != "1.1.1" {
		t.Fatalf("id/version = %q@%q, want ferroamp@1.1.1 — the installer "+
			"compares these against the manifest and refuses the artifact when they are empty",
			e.ID, e.Version)
	}
	if !e.ReadOnly {
		t.Error("read_only must survive the alias: the installer checks it against the manifest")
	}
	if got, want := e.VerificationStatus, "experimental"; got != want {
		t.Errorf("VerificationStatus = %q, want %q", got, want)
	}
	if len(e.Capabilities) != 3 {
		t.Errorf("Capabilities = %v, want battery/meter/pv", e.Capabilities)
	}
}

// The bundled drivers write the table inline, and that must keep working.
func TestParseCatalogFileStillReadsInlineTable(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, `DRIVER = {
    id = "inline",
    version = "2.0.0",
    protocols = { "modbus" },
}

function driver_poll(ctx) return {} end
`))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "inline" || e.Version != "2.0.0" {
		t.Fatalf("id/version = %q@%q, want inline@2.0.0", e.ID, e.Version)
	}
}

// An assignment that names nothing parseable should stay empty rather than
// pick up whatever table happens to be nearby.
func TestParseCatalogFileIgnoresAnAliasWithNoTable(t *testing.T) {
	e, err := ParseCatalogFile(writeLua(t, `local other = {
    id = "not-the-driver",
    version = "9.9.9",
}
DRIVER = missing_table
`))
	if err != nil {
		t.Fatalf("ParseCatalogFile: %v", err)
	}
	if e.ID != "" || e.Version != "" {
		t.Fatalf("id/version = %q@%q, want empty — a dangling alias must not "+
			"borrow another table's identity", e.ID, e.Version)
	}
}
