// Code generated by gencontract from contract/push-catalogue.yaml. DO NOT EDIT.

package notifications

// PushCatalogueVersion is the catalogue revision these sentences came from.
const PushCatalogueVersion = 1

// Push event kinds. Hand-writing one of these strings is what the
// catalogue exists to stop.
const (
	PushChargingConnected       = "charging.connected"
	PushChargingSessionComplete = "charging.session_complete"
	PushChargingInterrupted     = "charging.interrupted"
	PushUpdateInstalled         = "update.installed"
	PushDriverOffline           = "driver.offline"
	PushFuseOverLimit           = "fuse.over_limit"
	PushBoxUnreachable          = "box.unreachable"
)

// PushSentence is one lock-screen sentence, exactly as the app wrote it.
// {arg} placeholders are filled from the event's own facts and nothing else.
type PushSentence struct {
	Title string
	Body  string
}

// PushSentences is every sentence a push may carry, keyed by kind.
var PushSentences = map[string]PushSentence{
	PushChargingConnected:       {Title: "Car plugged in", Body: "Open to see charging status, check the battery level and set a ready time."},
	PushChargingSessionComplete: {Title: "Car charged", Body: "{kwh} kWh delivered — ready to go."},
	PushChargingInterrupted:     {Title: "Charging stopped early", Body: "The car stopped charging before it was done."},
	PushUpdateInstalled:         {Title: "Your box updated itself", Body: "Now running {version}. Everything came back on its own."},
	PushDriverOffline:           {Title: "A device went quiet", Body: "{name} stopped answering."},
	PushFuseOverLimit:           {Title: "The house is drawing too much", Body: "{phase} is over the fuse rating."},
	PushBoxUnreachable:          {Title: "Your box is out of reach", Body: "It stopped answering. Power cut, or the internet at home is down."},
}
