#!/usr/bin/env bash
set -euo pipefail

# Adds the optimizer sidecar to an older Compose installation without rewriting
# its base file. The updater auto-discovers docker-compose.override.yml, so all
# later selective updates see the same merged project.

base="${1:-docker-compose.yml}"
base_dir="$(dirname "${base}")"
override="${base_dir}/docker-compose.override.yml"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required" >&2
  exit 1
fi
if [ ! -f "${base}" ]; then
  echo "compose file not found: ${base}" >&2
  exit 1
fi
compose_args=(-f "${base}")
existing_overrides=()
for name in \
  docker-compose.override.yml \
  docker-compose.override.yaml \
  compose.override.yml \
  compose.override.yaml; do
  candidate="${base_dir}/${name}"
  if [ -e "${candidate}" ]; then
    existing_overrides+=("${candidate}")
    compose_args+=(-f "${candidate}")
  fi
done

services="$(docker compose "${compose_args[@]}" config --services)"
if grep -qx 'ftw-optimizer' <<<"${services}"; then
  echo "${base} already has the modular optimizer service in its merged Compose project"
  exit 0
fi
if [ "${#existing_overrides[@]}" -gt 0 ]; then
  printf 'refusing to overwrite or bypass existing Compose override(s):\n' >&2
  printf '  %s\n' "${existing_overrides[@]}" >&2
  echo "merge the modular optimizer service manually, then rerun this command" >&2
  exit 1
fi

main="${FTW_MAIN_SERVICE:-}"
if [ -z "${main}" ]; then
  if grep -qx 'ftw' <<<"${services}" && ! grep -qx 'forty-two-watts' <<<"${services}"; then
    main="ftw"
  elif grep -qx 'forty-two-watts' <<<"${services}" && ! grep -qx 'ftw' <<<"${services}"; then
    main="forty-two-watts"
  else
    echo "cannot select one core service; set FTW_MAIN_SERVICE explicitly" >&2
    exit 1
  fi
fi

tmp="${override}.tmp"
cleanup() { rm -f "${tmp}"; }
trap cleanup EXIT

{
  echo '# Generated by scripts/enable-modular-stack.sh'
  echo 'services:'
  echo "  ${main}:"
  echo '    environment:'
  echo '      FTW_OPTIMIZER_TRANSPORT: ${FTW_OPTIMIZER_TRANSPORT:-unix}'
  echo '      FTW_OPTIMIZER_SOCKET: /run/ftw-optimizer/optimizer.sock'
  echo '    volumes:'
  echo '      - optimizer-ipc:/run/ftw-optimizer'
  echo '  ftw-optimizer:'
  echo '    image: ghcr.io/srcfl/ftw-optimizer:${FTW_OPTIMIZER_IMAGE_TAG:-latest}'
  echo '    container_name: ftw-optimizer'
  echo '    restart: unless-stopped'
  echo '    network_mode: none'
  echo '    environment:'
  echo '      FTW_OPTIMIZER_SOCKET: /run/ftw-optimizer/optimizer.sock'
  echo '    volumes:'
  echo '      - optimizer-ipc:/run/ftw-optimizer'
  echo 'volumes:'
  echo '  optimizer-ipc:'
} >"${tmp}"

docker compose -f "${base}" -f "${tmp}" config >/dev/null
mv "${tmp}" "${override}"

if ! docker compose -f "${base}" -f "${override}" up -d ftw-optimizer "${main}"; then
  failed="${override}.failed"
  mv "${override}" "${failed}"
  docker compose -f "${base}" up -d "${main}" || true
  echo "modular startup failed; base stack restored and override kept at ${failed}" >&2
  exit 1
fi

echo "Modular optimizer enabled in ${override}. Core keeps its Go-DP fallback."
