#!/usr/bin/env bash
set -euo pipefail

# Adds the optimizer sidecar to an older Compose installation without rewriting
# its base file. The updater auto-discovers docker-compose.override.yml, so all
# later selective updates see the same merged project.

base="${1:-docker-compose.yml}"
override="$(dirname "${base}")/docker-compose.override.yml"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required" >&2
  exit 1
fi
if [ ! -f "${base}" ]; then
  echo "compose file not found: ${base}" >&2
  exit 1
fi
if grep -q '^  ftw-optimizer:' "${base}"; then
  echo "${base} already contains the modular optimizer service"
  exit 0
fi
if [ -e "${override}" ]; then
  echo "refusing to overwrite existing ${override}; merge the modular service manually" >&2
  exit 1
fi

services="$(docker compose -f "${base}" config --services)"
main="${FTW_MAIN_SERVICE:-}"
if [ -z "${main}" ]; then
  if grep -qx 'ftw' <<<"${services}" && ! grep -qx 'forty-two-watts' <<<"${services}"; then
    main="ftw"
  elif grep -qx 'forty-two-watts' <<<"${services}" && ! grep -qx 'ftw' <<<"${services}"; then
    main="forty-two-watts"
  else
    echo "cannot select one core service; set FTW_MAIN_SERVICE explicitly" >&2
    exit 1
  fi
fi

tmp="${override}.tmp"
cleanup() { rm -f "${tmp}"; }
trap cleanup EXIT

{
  echo '# Generated by scripts/enable-modular-stack.sh'
  echo 'services:'
  echo "  ${main}:"
  echo '    environment:'
  echo '      FTW_OPTIMIZER_TRANSPORT: ${FTW_OPTIMIZER_TRANSPORT:-auto}'
  echo '      FTW_OPTIMIZER_SOCKET: /run/ftw-optimizer/optimizer.sock'
  echo '    volumes:'
  echo '      - optimizer-ipc:/run/ftw-optimizer'
  echo '  ftw-optimizer:'
  echo '    image: ghcr.io/srcfl/ftw-optimizer:${FTW_OPTIMIZER_IMAGE_TAG:-latest}'
  echo '    container_name: ftw-optimizer'
  echo '    restart: unless-stopped'
  echo '    network_mode: none'
  echo '    environment:'
  echo '      FTW_OPTIMIZER_SOCKET: /run/ftw-optimizer/optimizer.sock'
  echo '    volumes:'
  echo '      - optimizer-ipc:/run/ftw-optimizer'
  echo 'volumes:'
  echo '  optimizer-ipc:'
} >"${tmp}"

docker compose -f "${base}" -f "${tmp}" config >/dev/null
mv "${tmp}" "${override}"

if ! docker compose -f "${base}" -f "${override}" up -d ftw-optimizer "${main}"; then
  failed="${override}.failed"
  mv "${override}" "${failed}"
  docker compose -f "${base}" up -d "${main}" || true
  echo "modular startup failed; base stack restored and override kept at ${failed}" >&2
  exit 1
fi

echo "Modular optimizer enabled in ${override}. Core keeps its process/Go-DP fallbacks."
